service: serverless-app

package:
  include:
    - backend/**    
  exclude:
    - frontend/** 
    - node_modules/** 

provider:
  profile: khangtruong0503
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true

  # you can overwrite defaults here
  stage: dev
  region: ap-southeast-1
  environment:
    USER_POOL_ID: !Ref CognitoUserPool
    USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient

plugins:
  - serverless-s3-sync
  - serverless-stack-termination-protection

custom:
  s3HostingName: ${self:service}-${self:provider.stage}-s3-hosting
  s3Sync:
    - bucketName: ${self:custom.s3HostingName}
      bucketPrefix: ''
      localDir: frontend/build
  serverlessTerminationProtection: 
    stages: 
      - prod 
      - live 
      - stg 
      - dev 

functions:
  registeredOnly:
    handler: backend/handler.requireLoggedIn
    events:
      - http:
          path: /logged-in
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

# you can add CloudFormation resource templates here
resources:
  # - Resources: ${file(serverlessAlarm.yml)}
  - Resources: ${file(serverlessCognito.yml)}
  - Resources: ${file(serverlessS3Hosting.yml)}